# docker/linux/aarch64/Dockerfile.test
# Purpose: Test environment for Linux aarch64 binary
# Usage:
# 1. Make sure binary is built using aarch64 builder
# 2. docker build --platform linux/arm64 -t spacejar/linux-aarch64-test -f docker/linux/aarch64/Dockerfile.test .
# 3. docker run --rm -it spacejar/linux-aarch64-test

FROM --platform=linux/arm64 ubuntu:latest

# Update package lists and install basic utilities
# Using apt-get is preferred in Dockerfiles over apt
RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce image size

WORKDIR /app
COPY binaries/linux/aarch64-unknown-linux-musl/spacejar /usr/local/bin/
RUN chmod +x /usr/local/bin/spacejar

ENTRYPOINT ["/bin/bash"]