name: Default SpaceJar Project
version: 0.1.0
description: A default SpaceJar project
author: SpaceJar User
license: Apache License 2.0
tags:
- Machine Learning
- AI
hardware:
  parallelism:
    min: 1
    recommended: 1
  cpu:
    min_cores: 2
    min_speed: 2.0
    recommended_cores: 8
    recommended_speed: 3.0
    architecture: x86_64
  gpu:
    required: false
    min_vram: 4
    recommended_vram: 24
    cuda_cores: 1000
    min_compute_capability: 3.5
    recommended_compute_capability: 6.0
    recommended_gpu: NVIDIA RTX 3090
  memory:
    min_ram: 16
    min_swap: 4
    recommended_swap: 16
    ram_type: DDR4
  storage:
    min_space: 100
    recommended_space: 1000
    type: SSD
    min_iops: 1000
    recommended_iops: 10000
  os:
    base_image: ubuntu:20.04
    label: ubuntu 20.04
data: []
