name: Release

on:
  release:
    types:
      - created

jobs:
  upload_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rust/binaries
          for file in $(find . -type f \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" \)); do
            echo "Uploading $file..."
            gh release upload "${{ github.event.release.tag_name }}" "$file" --clobber
          done