name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload_assets:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Delete release if it exists
          gh release delete ${{ github.ref_name }} --yes || true
          
          # Create new release without generating source archives
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Binary release for ${{ github.ref_name }}" \
            --prerelease=${{ contains(github.ref_name, '-test') }} \
            --verify-tag \
            --repo ${{ github.repository }}

      - name: Upload Assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd rust/binaries
          find . -type f \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" \) | while read file; do
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file" --clobber
          done