name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Upload binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Retrieve the latest tag (e.g. v0.1.0)
          TAG_NAME=$(basename "${GITHUB_REF}")

          # Create the release if it doesn't exist
          gh release create "$TAG_NAME" -t "$TAG_NAME" -n "Release $TAG_NAME"

          # Upload the binaries to the release
          for filepath in binaries/**/*.{tar.gz,zip}; do
            [ -f "$filepath"] && gh release upload "$TAG_NAME" "$filepath"
          done
